[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract = "HQVFLU86z6vUQLgUpoaa1aW2DGPvvnw9PVfxpvcudYAF"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
